# Generated by Django 3.0.4 on 2020-03-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='compound_id',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='id',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='smiles',
        ),
        migrations.AddField(
            model_name='compound',
            name='compound_smiles',
            field=models.CharField(default='', max_length=180, verbose_name='Compound SMILES'),
        ),
        migrations.AddField(
            model_name='compound',
            name='compoundcode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CompoundCode'),
        ),
        migrations.AddField(
            model_name='compound',
            name='confidence_annotation',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Confidence annotation'),
        ),
        migrations.AddField(
            model_name='compound',
            name='crystal_id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False, verbose_name='Crystal ID'),
        ),
        migrations.AddField(
            model_name='compound',
            name='datasetcluster',
            field=models.IntegerField(default=0, verbose_name='DatasetCluster'),
        ),
        migrations.AddField(
            model_name='compound',
            name='initial_occupancy_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='initial occupancy estimate'),
        ),
        migrations.AddField(
            model_name='compound',
            name='library_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Library Name'),
        ),
        migrations.AddField(
            model_name='compound',
            name='map_resol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Map Resol'),
        ),
        migrations.AddField(
            model_name='compound',
            name='modified_compound_smiles',
            field=models.CharField(max_length=180, null=True, verbose_name='Modified Compound Smiles'),
        ),
        migrations.AddField(
            model_name='compound',
            name='peak_height_z_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='peak-height z-value'),
        ),
        migrations.AddField(
            model_name='compound',
            name='site',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='compound',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Status'),
        ),
    ]
